### ISSUE TITLE
click

### ISSUE THREAD

**Issue by AmpPy** [KianBrose/Image-Recognition-Botting-Tutorial#8]
doesnt click

**Comment by stefanlnt23** [comment]
just do like this:

while keyboard.is_pressed ('q')== False:
    if pyautogui.pixel(1319,418)[0]==0:
        click(1319,418)
        click(1319,418)
        click(1320,418)
        click(1318,418)
        click(1316,418)
        click(1315,418)
        click(1319,418)
        click(1319,418)
        click(1319,418)
        click(1321,418)
        click(1320,418)

    if pyautogui.pixel(1410,425)[0]==0:
        click(1411,425)
        click(1414,425)
        click(1410,425)
        click(1410,425)
        click(1412,425)
        click(1410,425)
        click(1410,425)
        click(1413,425)
        click(1409,425)
        click(1408,425)
        click(1411,425)
    if pyautogui.pixel(1512,428)[0]==0:
        click(1512,428)
        click(1508,428)
        click(1514,428)
        click(1512,428)
        click(1512,428)
        click(1508,428)
        click(1512,428)
        click(1510,428)
        click(1512,428)
        click(1509,428)
        click(1512,428)
    if pyautogui.pixel(1600,428)[0]==0:
        click(1607,428)
        click(1600,428)
        click(1604,428)
        click(1601,428)
        click(1603,428)
        click(1600,428)
        click(1602,428)
        click(1601,428)
        click(1605,428)
        click(1606,428)
        click(1600,428)

**Comment by KianBrose** [comment]
Em actually theres an issue where the delay in the click function is too small for the browser to interpret

**Comment by KianBrose** [comment]
Fixed
